apiVersion: apps/v1
kind: Deployment
metadata:
  name: cheer-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheer-gateway
  template:
    metadata:
      labels:
        app: cheer-gateway
    spec:
      containers:
        - name: cheer-gateway
          image: ssohy/cheer-gateway:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: gateway-secret
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: cheer-gateway
  labels:
    app: cheer-gateway
spec:
  selector:
    app: cheer-gateway
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
